language: node_js

node_js:
  - "10"
  - "11"
  - "12"

env:
  global:
    - NODE_ENV=test

before_script:

script:
  - "npm run rebuild"

after_success:
  - "npm run coveralls"

install:
  - npm install

notifications:
  email:
    - dieter.oberkofler@gmail.com
