language: node_js

node_js:
  - "8"
  - "9"

env:
  global:
    - NODE_ENV=test

before_script:

script:
  - "npm run rebuild"

after_success:
  - 'if [ "$node_js" = "8" ]; then npm run coveralls; fi'

install:
  - npm install

notifications:
  email:
    - dieter.oberkofler@gmail.com
