# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# What combinations to test
environment:
  NODE_ENV: test
  matrix:
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13

branches:
  only:
    - master

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - npm install

build: off

test_script:
  - npm run clean
  - npm run eslint
  - npm run build
  - npm run test

matrix:
  fast_finish: true    # set this flag to immediately finish build once one of the jobs fails.
